# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Crunchbase',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, max_length=10, null=True)),
                ('rank', models.TextField(blank=True, max_length=300, null=True)),
                ('category', models.TextField(blank=True, max_length=300, null=True)),
                ('location', models.TextField(blank=True, max_length=300, null=True)),
                ('website', models.TextField(blank=True, max_length=300, null=True)),
                ('facebook', models.TextField(blank=True, max_length=300, null=True)),
                ('twitter', models.TextField(blank=True, max_length=300, null=True)),
                ('linkdin', models.TextField(blank=True, max_length=300, null=True)),
                ('phone', models.TextField(blank=True, max_length=300, null=True)),
                ('email', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='People_Crunchbase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50, null=True)),
                ('gender', models.TextField(blank=True, max_length=10, null=True)),
                ('designation', models.TextField(blank=True, max_length=300, null=True)),
                ('first_name', models.TextField(blank=True, max_length=300, null=True)),
                ('last_name', models.TextField(blank=True, max_length=300, null=True)),
                ('rank', models.TextField(blank=True, max_length=300, null=True)),
                ('twitter', models.TextField(blank=True, max_length=300, null=True)),
                ('linkdin', models.TextField(blank=True, max_length=300, null=True)),
                ('facebook', models.TextField(blank=True, max_length=300, null=True)),
                ('location', models.TextField(blank=True, max_length=300, null=True)),
                ('biography', models.TextField(blank=True, max_length=500, null=True)),
                ('company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_users', to='api.Company_Crunchbase', unique=True)),
            ],
        ),
    ]
