# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170321_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people_crunchbase',
            name='id',
        ),
        migrations.AlterField(
            model_name='people_crunchbase',
            name='company',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='people_crunchbase',
            name='name',
            field=models.TextField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
