# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-23 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170322_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_crunchbase',
            name='last_funding_type',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company_crunchbase',
            name='status',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
