# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-23 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170323_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='AngellistCompany',
            fields=[
                ('name', models.TextField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
